### ISSUE TITLE
Spotify 2020 parsing

### ISSUE THREAD

**Issue by technomorph** [mikez/spotify-folders#2]
I’m getting issues now unless the folder has a sub folder it’s URI and name get messed up.

**Comment by technomorph** [comment]
Figured it out.  I think because Spotify removed the "user" requirement for the Web API for playlists.  Now in the cache it is being stored that way.

I found via Logging that Folder Row was still including after the name of the Folder
"spotify:playlist:xxxxxxx" etc.

so I added a 'p' in the regex split :

`rows = re.split(b'spotify:[usep]', data)`

this now works as it should.

**Comment by technomorph** [comment]
Oh except now it's not adding the playlist Children properly.

i've adjusted to:

 `       if row.startswith(b'laylist:'):`

and now it adds the playlist children fine.

**Comment by mikez** [comment]
🙏 @technomorph for reporting. Does the new fix work for you?
