### ISSUE TITLE
Error Decoding Playlist

### ISSUE THREAD

**Issue by ShiromMakkad** [mikez/spotify-folders#5]
I'm getting an invalid start byte error when decoding the spotify uri

```
Traceback (most recent call last):
  File "./spotifyfolders", line 198, in <module>
    print(_process(cache_file_name, args))
  File "./spotifyfolders", line 144, in _process
    data = parse(file_name, user_id=user_id)
  File "./spotifyfolders", line 63, in parse
    'uri': 'spotify:' + row[:-1].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 33: invalid start byte
```

The line numbers will be a bit off since I modified the script to read from my local directory:
```
# PERSISTENT_CACHE_PATH = (
#     MAC_PERSISTENT_CACHE_PATH if sys.platform == 'darwin'
#     else LINUX_PERSISTENT_CACHE_PATH)
PERSISTENT_CACHE_PATH = (
    './Storage')
```
I'm running the script in WSL and I've copied my Windows storage folder  into the directory where the script is. It seems to recognize the folder just fine, so I don't think this modification is the issue. Do you know how to fix this error?

**Comment by mikez** [comment]
I'm not familiar with WSL, Shirom, but maybe I can still help. I sent you an email with next steps for troubleshooting.

**Comment by mikez** [comment]
> Do you know how to fix this error?

The error might point towards a folder name which exceeds 128 (byte) characters. If you're using a non-latin script, this might happen more quickly. I'm happy to coach you through how to modify the script, but it will require some work.

**Comment by mikez** [comment]
I pushed a new update, @ShiromMakkad. Let me know if this works for you!

**Comment by ShiromMakkad** [comment]
Works perfectly, thanks for your help!
