### ISSUE TITLE
Provide explanation how to find the Spotify Cache folder

### ISSUE THREAD

**Issue by KuSi833** [mikez/spotify-folders#7]
The app couldn't automatically find my Spotify Cache folder on Windows, and I didn't find it immediately obvious to which folder to point the `--cache` option to. It might be useful to add to the `--cache` option description that it can be found under `Settings` -> `Offline storage location` ?

**Comment by mikez** [comment]
@KuSi833 I appreciate your comment about `Settings -> Offline storage location`. The app currently only supports macOS and Linux, however there has been some discussion about also supporting Windows here: https://github.com/mikez/spotify-folders/issues/6#issuecomment-1114093806

**Comment by mikez** [comment]
@KuSi833 The app now supports Windows. I added `Settings -> Offline storage location` to the help message which appears if no cache files were found.

```
$ spotifyfolders --cache /dev/null
No data found in Spotify cache. If you have a custom cache directory set,
specify its path with the `--cache` flag. Also, in the Spotify app,
check Settings -> Offline storage location.
```
